<?php

namespace Database\Seeders;

use App\Models\HomeSectionItem;
use Illuminate\Database\Seeder;

class HomeSectionItemSeeder extends Seeder
{
    public function run(): void
    {
        HomeSectionItem::truncate();

        $items = [
            // ───── Hero Slider (3 Slides) ─────
            [
                'section'     => 'hero_slider',
                'title'       => 'The Roots Are with fruits',
                'subtitle'    => 'As fresh as Fruit',
                'description' => 'The more you love your health, more you eat organic. No medicine can heal you better than organic food does',
                'button_text' => 'Shop Now',
                'button_url'  => '#',
                'image'       => 'img/slider/home4-slider1.png',
                'sort_order'  => 1,
                'is_active'   => true,
            ],
            [
                'section'     => 'hero_slider',
                'title'       => 'The Roots Are with fruits',
                'subtitle'    => 'As fresh as Fruit',
                'description' => 'The more you love your health, more you eat organic. No medicine can heal you better than organic food does',
                'button_text' => 'Shop Now',
                'button_url'  => '#',
                'image'       => 'img/slider/home4-slider2.png',
                'sort_order'  => 2,
                'is_active'   => true,
            ],
            [
                'section'     => 'hero_slider',
                'title'       => 'The Roots Are with fruits',
                'subtitle'    => 'As fresh as Fruit',
                'description' => 'The more you love your health, more you eat organic. No medicine can heal you better than organic food does',
                'button_text' => 'Shop Now',
                'button_url'  => '#',
                'image'       => 'img/slider/home4-slider3.png',
                'sort_order'  => 3,
                'is_active'   => true,
            ],

            // ───── Our Collection (7 Instagram Photos) ─────
            [
                'section'     => 'collection',
                'title'       => 'Organic Greens & Bowls',
                'button_url'  => 'https://www.instagram.com/p/CZkF3TLBTT7',
                'image'       => 'img/other/instagram1.webp',
                'sort_order'  => 1,
                'is_active'   => true,
            ],
            [
                'section'     => 'collection',
                'title'       => 'Fresh Berry Collection',
                'button_url'  => 'https://www.instagram.com/p/CZkF60sBxhN',
                'image'       => 'img/other/instagram2.webp',
                'sort_order'  => 2,
                'is_active'   => true,
            ],
            [
                'section'     => 'collection',
                'title'       => 'Herbal Teas & Infusions',
                'button_url'  => 'https://www.instagram.com/p/CZkF90ZB6HG',
                'image'       => 'img/other/instagram3.webp',
                'sort_order'  => 3,
                'is_active'   => true,
            ],
            [
                'section'     => 'collection',
                'title'       => 'Citrus Farm Bounty',
                'button_url'  => 'https://www.instagram.com/p/CZkGAe6BQeu',
                'image'       => 'img/other/instagram4.webp',
                'sort_order'  => 4,
                'is_active'   => true,
            ],
            [
                'section'     => 'collection',
                'title'       => 'Cold Pressed Oils',
                'button_url'  => 'https://www.instagram.com/p/CZkGCWcBbv9',
                'image'       => 'img/other/instagram5.webp',
                'sort_order'  => 5,
                'is_active'   => true,
            ],
            [
                'section'     => 'collection',
                'title'       => 'Artisanal Herbal Jars',
                'button_url'  => 'https://www.instagram.com/p/CZkGFDMhoid',
                'image'       => 'img/other/instagram6.webp',
                'sort_order'  => 6,
                'is_active'   => true,
            ],
            [
                'section'     => 'collection',
                'title'       => 'Pure Botanical Extract',
                'button_url'  => 'https://www.instagram.com/p/CZkGGnyh7jZ',
                'image'       => 'img/other/instagram7.webp',
                'sort_order'  => 7,
                'is_active'   => true,
            ],

            // ───── Best Selling Products (8 Products) ─────
            [
                'section'         => 'best_selling',
                'title'           => 'Green-surface',
                'price'           => '₹38.00',
                'old_price'       => '₹40.00',
                'badge'           => 'Sale',
                'rating'          => 5,
                'image'           => 'img/product/product7.png',
                'secondary_image' => 'img/product/product8.png',
                'button_url'      => 'product-details.html',
                'sort_order'      => 1,
                'is_active'       => true,
            ],
            [
                'section'         => 'best_selling',
                'title'           => 'Fresh Lemon Juice',
                'price'           => '$42.00',
                'old_price'       => '$45.00',
                'badge'           => 'New',
                'rating'          => 5,
                'image'           => 'img/product/product8.png',
                'secondary_image' => 'img/product/product9.png',
                'button_url'      => 'product-details.html',
                'sort_order'      => 2,
                'is_active'       => true,
            ],
            [
                'section'         => 'best_selling',
                'title'           => 'Organic Red Apple',
                'price'           => '$25.00',
                'old_price'       => '$30.00',
                'badge'           => '-15%',
                'rating'          => 4,
                'image'           => 'img/product/product9.png',
                'secondary_image' => 'img/product/product10.png',
                'button_url'      => 'product-details.html',
                'sort_order'      => 3,
                'is_active'       => true,
            ],
            [
                'section'         => 'best_selling',
                'title'           => 'Fresh Sweet Watermelon',
                'price'           => '$19.00',
                'old_price'       => '$22.00',
                'badge'           => 'Sale',
                'rating'          => 5,
                'image'           => 'img/product/product10.png',
                'secondary_image' => 'img/product/product11.png',
                'button_url'      => 'product-details.html',
                'sort_order'      => 4,
                'is_active'       => true,
            ],
            [
                'section'         => 'best_selling',
                'title'           => 'Organic Fresh Orange',
                'price'           => '$32.00',
                'old_price'       => '$35.00',
                'badge'           => null,
                'rating'          => 5,
                'image'           => 'img/product/product11.png',
                'secondary_image' => 'img/product/product12.png',
                'button_url'      => 'product-details.html',
                'sort_order'      => 5,
                'is_active'       => true,
            ],
            [
                'section'         => 'best_selling',
                'title'           => 'Fresh Golden Pineapple',
                'price'           => '$15.00',
                'old_price'       => '$18.00',
                'badge'           => 'Sale',
                'rating'          => 4,
                'image'           => 'img/product/product12.png',
                'secondary_image' => 'img/product/product7.png',
                'button_url'      => 'product-details.html',
                'sort_order'      => 6,
                'is_active'       => true,
            ],
            [
                'section'         => 'best_selling',
                'title'           => 'Natural Green Grapes',
                'price'           => '$28.00',
                'old_price'       => '$30.00',
                'badge'           => 'New',
                'rating'          => 5,
                'image'           => 'img/product/product7.png',
                'secondary_image' => 'img/product/product8.png',
                'button_url'      => 'product-details.html',
                'sort_order'      => 7,
                'is_active'       => true,
            ],
            [
                'section'         => 'best_selling',
                'title'           => 'Sweet Organic Strawberry',
                'price'           => '$20.00',
                'old_price'       => '$24.00',
                'badge'           => 'Sale',
                'rating'          => 5,
                'image'           => 'img/product/product8.png',
                'secondary_image' => 'img/product/product9.png',
                'button_url'      => 'product-details.html',
                'sort_order'      => 8,
                'is_active'       => true,
            ],

            // ───── Our Products / Monthly Specials (8 Products) ─────
            [
                'section'         => 'our_products',
                'title'           => 'Special Avocado Box',
                'price'           => '$45.00',
                'old_price'       => '$50.00',
                'badge'           => 'Hot',
                'rating'          => 5,
                'image'           => 'img/product/product1.png',
                'secondary_image' => 'img/product/product2.png',
                'button_url'      => 'product-details.html',
                'sort_order'      => 1,
                'is_active'       => true,
            ],
            [
                'section'         => 'our_products',
                'title'           => 'Pure Herbal Infusion',
                'price'           => '₹35.00',
                'old_price'       => '₹40.00',
                'badge'           => 'Sale',
                'rating'          => 5,
                'image'           => 'img/product/product2.png',
                'secondary_image' => 'img/product/product3.png',
                'button_url'      => 'product-details.html',
                'sort_order'      => 2,
                'is_active'       => true,
            ],
            [
                'section'         => 'our_products',
                'title'           => 'Wild Floral Raw Honey',
                'price'           => '$55.00',
                'old_price'       => '$60.00',
                'badge'           => 'New',
                'rating'          => 5,
                'image'           => 'img/product/product3.png',
                'secondary_image' => 'img/product/product4.png',
                'button_url'      => 'product-details.html',
                'sort_order'      => 3,
                'is_active'       => true,
            ],
            [
                'section'         => 'our_products',
                'title'           => 'Natural Aloe Essence',
                'price'           => '$22.00',
                'old_price'       => '$26.00',
                'badge'           => '-20%',
                'rating'          => 4,
                'image'           => 'img/product/product4.png',
                'secondary_image' => 'img/product/product5.png',
                'button_url'      => 'product-details.html',
                'sort_order'      => 4,
                'is_active'       => true,
            ],
            [
                'section'         => 'our_products',
                'title'           => 'Herbal Mint Extract',
                'price'           => '$29.00',
                'old_price'       => '$34.00',
                'badge'           => 'Sale',
                'rating'          => 5,
                'image'           => 'img/product/product5.png',
                'secondary_image' => 'img/product/product6.png',
                'button_url'      => 'product-details.html',
                'sort_order'      => 5,
                'is_active'       => true,
            ],
            [
                'section'         => 'our_products',
                'title'           => 'Sun-Dried Organic Figs',
                'price'           => '$39.00',
                'old_price'       => '$44.00',
                'badge'           => null,
                'rating'          => 5,
                'image'           => 'img/product/product6.png',
                'secondary_image' => 'img/product/product1.png',
                'button_url'      => 'product-details.html',
                'sort_order'      => 6,
                'is_active'       => true,
            ],
            [
                'section'         => 'our_products',
                'title'           => 'Roasted Almond Delight',
                'price'           => '$48.00',
                'old_price'       => '$52.00',
                'badge'           => 'Hot',
                'rating'          => 5,
                'image'           => 'img/product/product1.png',
                'secondary_image' => 'img/product/product2.png',
                'button_url'      => 'product-details.html',
                'sort_order'      => 7,
                'is_active'       => true,
            ],
            [
                'section'         => 'our_products',
                'title'           => 'Virgin Coconut Oil',
                'price'           => '₹36.00',
                'old_price'       => '₹40.00',
                'badge'           => 'New',
                'rating'          => 5,
                'image'           => 'img/product/product2.png',
                'secondary_image' => 'img/product/product3.png',
                'button_url'      => 'product-details.html',
                'sort_order'      => 8,
                'is_active'       => true,
            ],

            // ───── Testimonials (3 Client Reviews) ─────
            [
                'section'     => 'testimonial',
                'title'       => 'JACKLY SMITH',
                'subtitle'    => 'Senior Manager',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt dolor sit amet, consectetur',
                'rating'      => 5,
                'image'       => 'img/other/testimonial-thumb1.png',
                'sort_order'  => 1,
                'is_active'   => true,
            ],
            [
                'section'     => 'testimonial',
                'title'       => 'Laura Johnson',
                'subtitle'    => 'Products Manager',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt dolor sit amet, consectetur',
                'rating'      => 5,
                'image'       => 'img/other/testimonial-thumb2.png',
                'sort_order'  => 2,
                'is_active'   => true,
            ],
            [
                'section'     => 'testimonial',
                'title'       => 'Richard Smith',
                'subtitle'    => 'CEO - Founder',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt dolor sit amet, consectetur',
                'rating'      => 5,
                'image'       => 'img/other/testimonial-thumb3.png',
                'sort_order'  => 3,
                'is_active'   => true,
            ],
        ];

        foreach ($items as $item) {
            HomeSectionItem::create($item);
        }
    }
}
